INSERT INTO
    `movies` (
        `id`,
        `title`,
        `release_data`,
        `rating`,
        `duration`,
        `description`,
        `filename`,
        `poster_url`,
        `likes`
    )
VALUES (
        1,
        'The Shawshank Redemption',
        '1994-09-23',
        9.2,
        142,
        'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
        '1.mp4',
        '1.webp',
        0
    ),
    (
        2,
        'The Godfather',
        '1972-03-15',
        9.2,
        175,
        'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
        '2.mp4',
        '2.webp',
        0
    ),
    (
        3,
        'The Dark Knight',
        '2008-07-18',
        9.0,
        162,
        'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        '3.mp4',
        '3.webp',
        0
    ),
    (
        4,
        '12 Angry Men',
        '1957-04-10',
        9.0,
        96,
        'A jury holdout attempts to convince the other jurors that the defendant is innocent of murder.',
        '4.mp4',
        '4.webp',
        0
    ),
    (
        5,
        'Schindler\'s List',
        '1993-12-15',
        8.9,
        195,
        'In Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
        '5.mp4',
        '5.webp',
        0
    ),
    (
        6,
        'The Lord of the Rings: The Return of the King',
        '2003-12-01',
        8.9,
        201,
        'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw their gaze away from Frodo and Sam as they approach Mount Doom with the One Ring.',
        '6.mp4',
        '6.webp',
        0
    ),
    (
        7,
        'Pulp Fiction',
        '1994-10-14',
        8.8,
        174,
        'The lives of two mob hitmen, a boxer, a pair of diner bandits, and a pair of philosophical hitmen intertwine in four tales of violence and redemption.',
        '7.mp4',
        '7.webp',
        0
    ),
    (
        8,
        'The Lord of the Rings: The Fellowship of the Ring',
        '2001-12-19',
        8.8,
        178,
        'A hobbit, a wizard, a dwarf, and a human embark on a perilous journey to destroy the One Ring and save Middle-earth from the dark lord Sauron.',
        '8.mp4',
        '8.webp',
        0
    ),
    (
        9,
        'Forrest Gump',
        '1994-07-06',
        8.8,
        142,
        'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold through the perspective of an Alabama man with a low IQ.',
        '9.mp4',
        '9.webp',
        0
    ),
    (
        10,
        'Star Wars: Episode V - The Empire Strikes Back',
        '1980-06-20',
        8.8,
        124,
        'After the destruction of the Death Star, Imperial forces pursue Luke Skywalker and the Rebel Alliance to the ice planet Hoth. Darth Vader is obsessed with finding Luke.',
        '10.mp4',
        '10.webp',
        0
    ),
    (
        11,
        'The Lord of the Rings: The Two Towers',
        '2002-12-18',
        8.7,
        179,
        'Frodo and Sam continue their journey to destroy the One Ring and are aided by the wizard Gandalf, the human warrior Aragorn, the elf Legolas, and Gimli the dwarf.',
        '11.mp4',
        '11.webp',
        0
    ),
    (
        12,
        'One Flew Over the Cuckoo\'s Nest',
        '1975-11-19',
        8.7,
        133,
        'A group of psychiatric patients are threatened by a strict nurse and form an unlikely alliance with a charismatic newcomer.',
        '12.mp4',
        '12.webp',
        0
    ),
    (
        13,
        'The Matrix',
        '1999-03-31',
        8.7,
        136,
        'A computer hacker learns from the resistance fighters about the true nature of his reality and his role in the war against its creators.',
        '13.mp4',
        '13.webp',
        0
    ),
    (
        14,
        'Goodfellas',
        '1990-09-19',
        8.7,
        146,
        'The story of Henry Hill and his life in the mob, covering his relationship with his wife and his mob partners Jimmy Conway and Tommy DeVito.',
        '14.mp4',
        '14.webp',
        0
    ),
    (
        15,
        'Seven Samurai',
        '1954-04-26',
        8.7,
        207,
        'A veteran samurai, who has lost his master and is adrift, answers a village\'s request for protection from bandits. He gathers 6 other samurai to help him, and they teach the peasants how to defend themselves, and they prepare for a final battle.',
        '15.mp4',
        '15.webp',
        0
    ),
    (
        16,
        'The Silence of the Lambs',
        '1991-02-14',
        8.6,
        118,
        'A young FBI agent seeks the advice of imprisoned serial killer Hannibal Lecter to apprehend another serial killer known as Buffalo Bill.',
        '16.mp4',
        '16.webp',
        0
    ),
    (
        17,
        'City of God',
        '2002-01-18',
        8.6,
        130,
        'In the slums of Rio, two kids\' paths diverge as one struggles to become a photographer and the other becomes a powerful crime lord.',
        '17.mp4',
        '17.webp',
        0
    ),
    (
        18,
        'Se7en',
        '1995-09-22',
        8.6,
        127,
        'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as a motif for his murders.',
        '18.mp4',
        '18.webp',
        0
    ),
    (
        19,
        'The Pianist',
        '2002-12-04',
        8.6,
        150,
        'A Polish Jewish pianist struggles to survive the Nazi occupation of Warsaw and the concentration camps.',
        '19.mp4',
        '19.webp',
        0
    ),
    (
        20,
        'The Prestige',
        '2006-10-20',
        8.6,
        130,
        'The rivalry between two magicians is exacerbated when one of them performs a trick which seems impossible.',
        '20.mp4',
        '20.webp',
        0
    ),
    (
        21,
        'Casablanca',
        '1942-11-26',
        8.5,
        102,
        'Set in Morocco during the early days of World War II: An American expatriate meets a former lover, with unforeseen complications.',
        '21.mp4',
        '21.webp',
        0
    ),
    (
        22,
        'The Green Mile',
        '1999-12-10',
        8.5,
        189,
        'The story of a death row supervisor who develops a bond with a man who possesses supernatural healing powers.',
        '22.mp4',
        '22.webp',
        0
    ),
    (
        23,
        'Apocalypse Now',
        '1979-08-15',
        8.5,
        153,
        'During the Vietnam War, a US Army officer is sent on a secret mission to assassinate a renegade American colonel who has set himself up as a god in a remote jungle area.',
        '23.mp4',
        '23.webp',
        0
    ),
    (
        24,
        'The Good, the Bad and the Ugly',
        '1966-12-23',
        8.5,
        161,
        'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune of gold buried in a remote cemetery.',
        '24.mp4',
        '24.webp',
        0
    ),
    (
        25,
        'Taxi Driver',
        '1976-02-08',
        8.5,
        113,
        'A mentally unstable Vietnam War veteran works as a night-time taxi driver in New York City, where the perceived decadence and sleaze feeds his urge for violent action.',
        '25.mp4',
        '25.webp',
        0
    ),
    (
        26,
        'Rear Window',
        '1954-09-01',
        8.5,
        112,
        'A wheelchair-bound photographer spies on his neighbors from his apartment window and becomes convinced one of them has committed a murder.',
        '26.mp4',
        '26.webp',
        0
    ),
    (
        27,
        'The Wizard of Oz',
        '1939-08-12',
        8.5,
        101,
        'A young girl is transported to a magical land, where she embarks on a quest to find the wizard who can help her return home.',
        '27.mp4',
        '27.webp',
        0
    ),
    (
        28,
        'Jaws',
        '1975-06-20',
        8.5,
        124,
        'A police chief, a marine biologist, and a fisherman team up to stop a great white shark that is terrorizing a beach town.',
        '28.mp4',
        '28.webp',
        0
    ),
    (
        29,
        'E.T. the Extra-Terrestrial',
        '1982-06-11',
        8.5,
        115,
        'A young boy befriends an alien who is stranded on Earth and tries to help him get back home.',
        '29.mp4',
        '29.webp',
        0
    ),
    (
        30,
        'The Terminator',
        '1984-10-26',
        8.4,
        107,
        'A cyborg is sent back in time to kill Sarah Connor, the mother of the future leader of the human resistance against machines, while a soldier is sent to protect her.',
        '30.mp4',
        '30.webp',
        0
    ),
    (
        31,
        'The Princess Bride',
        '1987-09-25',
        8.4,
        98,
        'Inconceivable! A beautiful princess, a gallant hero, a wicked villain, and a memorable supporting cast combine in a swashbuckling adventure.',
        '31.mp4',
        '31.webp',
        0
    ),
    (
        32,
        'The Silence of the Lambs',
        '1991-02-14',
        8.4,
        118,
        'A young FBI agent seeks the advice of imprisoned serial killer Hannibal Lecter to apprehend another serial killer known as Buffalo Bill.',
        '32.mp4',
        '32.webp',
        0
    ),
    (
        33,
        'The Matrix Revolutions',
        '2003-11-05',
        8.4,
        129,
        'The human city of Zion defends itself against the massive invasion of the machines, while Neo fights to end the war at another front while also opposing the rogue Agent Smith.',
        '33.mp4',
        '33.webp',
        0
    ),
    (
        34,
        'Blade Runner',
        '1982-06-25',
        8.4,
        117,
        'A blade runner must pursue and try to terminate four replicants who stole a ship in space and have returned to Earth to find their creator.',
        '34.mp4',
        '34.webp',
        0
    ),
    (
        35,
        'The Big Lebowski',
        '1998-03-06',
        8.4,
        117,
        'The \"Dude\", Jeff \"The Big\" Lebowski, is mistaken for a millionaire Lebowski, and accepts a private investigation job that leads him into a complex and wacky crime caper.',
        '35.mp4',
        '35.webp',
        0
    ),
    (
        36,
        'Sunrise: A Song of Two Humans',
        '1927-09-23',
        8.4,
        95,
        'A married farmer falls under the spell of a seductress from the city, who tries to convince him to murder his wife.',
        '36.mp4',
        '36.webp',
        0
    ),
    (
        37,
        'The Bridge on the River Kwai',
        '1957-12-11',
        8.4,
        161,
        'After settling his differences with a Japanese POW camp commander, a British colonel co-operates to oversee the construction of a railway bridge for their captors, while oblivious to a plan by the Allies to destroy it.',
        '37.mp4',
        '37.webp',
        0
    ),
    (
        38,
        'The 400 Blows',
        '1959-05-31',
        8.4,
        117,
        'A young boy is sent to a reform school after being caught stealing.',
        '38.mp4',
        '38.webp',
        0
    ),
    (
        39,
        'The Grapes of Wrath',
        '1940-01-24',
        8.4,
        129,
        'A poor Midwest family is forced off their farm and travels to California, suffering the misfortunes of the Great Depression.',
        '39.mp4',
        '39.webp',
        0
    ),
    (
        40,
        'The Maltese Falcon',
        '1941-10-03',
        8.4,
        100,
        'A private detective takes on a case in which a valuable statuette is the focal point.',
        '40.mp4',
        '40.webp',
        0
    ),
    (
        41,
        'The African Queen',
        '1951-12-23',
        8.4,
        105,
        'In Africa during WW1, a gin-swilling riverboat captain is persuaded by a strait-laced missionary to use his boat to attack an enemy warship.',
        '41.mp4',
        '41.webp',
        0
    ),
    (
        42,
        'Rashomon',
        '1950-08-25',
        8.4,
        88,
        'A heinous crime and its aftermath are recalled from different viewpoints.',
        '42.mp4',
        '42.webp',
        0
    ),
    (
        43,
        'The Battle of Algiers',
        '1966-08-31',
        8.4,
        121,
        'The epic story of a young Algerian\'s struggle against the French colonial occupation of his country.',
        '43.mp4',
        '43.webp',
        0
    ),
    (
        44,
        'Tokyo Story',
        '1953-11-03',
        8.4,
        134,
        'An aging couple visit their children and grandchildren in the city; but the children have little time for them.',
        '44.mp4',
        '44.webp',
        0
    ),
    (
        45,
        'The Seventh Seal',
        '1957-02-16',
        8.4,
        96,
        'A knight returns from the Crusades and challenges Death to a game of chess.',
        '45.mp4',
        '45.webp',
        0
    ),
    (
        46,
        'The Rules of the Game',
        '1939-07-07',
        8.4,
        110,
        'A bourgeois life in France at the onset of World War II, shown through the eyes of a jaded aristocrat.',
        '46.mp4',
        '46.webp',
        0
    ),
    (
        47,
        'The Wild Bunch',
        '1969-06-18',
        8.4,
        145,
        'An aging outlaw tries to find a way to live in a changing world.',
        '47.mp4',
        '47.webp',
        0
    ),
    (
        48,
        'The Man Who Shot Liberty Valance',
        '1962-04-22',
        8.4,
        123,
        'A senator, who became famous for killing a notorious outlaw, returns for the funeral of an old rancher and tells the story of his life.',
        '48.mp4',
        '48.webp',
        0
    ),
    (
        49,
        'The Lady from Shanghai',
        '1947-12-24',
        8.4,
        87,
        'Fascinated by gorgeous Mrs. Bannister, seaman Michael O\'Hara joins her yacht, and even helps her deceitful husband escape the Chinese authorities.',
        '49.mp4',
        '49.webp',
        0
    ),
    (
        50,
        'The Philadelphia Story',
        '1940-06-27',
        8.4,
        112,
        'When a woman\'s ex-husband shows up unexpectedly on the eve of her second marriage, she must decide between the two men she loves.',
        '50.mp4',
        '50.webp',
        0
    );